### ISSUE TITLE
Unable to run tests through remote ADB

### ISSUE THREAD

**Issue by davirss** [appium/appium-docker-android#116]
Hello!

I was able to successfully set up Appium-Docker as a node for my Selenium Grid. And I'm also using a remote ADB Server for the devices. Running "ADB devices" inside the container I'm able to check that the container can communicate with the devices. 

![image](https://user-images.githubusercontent.com/3461820/69233984-5060bc80-0b8e-11ea-8972-aa00b3cd24cf.png)

However, when running the tests, appium keeps restarting the ADB server and its not able to list the devices.

![image](https://user-images.githubusercontent.com/3461820/69233932-2c04e000-0b8e-11ea-8da7-bdecdde4e57f.png)

Does anyone have any idea why this is happening?
### My Environment:
- Windows x64 Machine Hyper-V Enabled
- Docker Version 2.1.0.5
- Both Container and ADB Server is in the same machine

### My yaml file
```
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-xenon
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-xenon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox:3.141.59-xenon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  appium_android_device:
    image: appium/appium
    depends_on:
      - selenium-hub
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
    environment:
      - ADB_SERVER_SOCKET=tcp:host.docker.internal:5037
      - APPIUM_HOST=appium_android_device
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium-hub
      #- CUSTOM_NODE_CONFIG=true
      - BROWSER_NAME=chrome
```

If any info is missing, let me know.
