### ISSUE TITLE
since `v1.22.3-p3` chromedriver autodownload does not work any more

### ISSUE THREAD

**Issue by mikk150** [appium/appium-docker-android#152]
since `v1.22.3-p3` `--allow-insecure chromedriver_autodownload` does not seem to work

```
version: "3.7"
services:
  appium:
    image: appium/appium:latest #if you use v1.22.3-p2 here instead, it works
    ports:
      - 4723
    environment:
      - CHROMEDRIVER_AUTODOWNLOAD=true
      - "APPIUM_ADDITIONAL_PARAMS= --allow-insecure chromedriver_autodownload"
      - REMOTE_ADB=true
      - ANDROID_DEVICES=redroid:5555
```
[working.log](https://github.com/appium/appium-docker-android/files/10569632/working.log)
[no_working.log](https://github.com/appium/appium-docker-android/files/10569637/no_working.log)
