### ISSUE TITLE
Is there possible way to implement appium/appium with IOS?

### ISSUE THREAD

**Issue by apxthexsis** [appium/appium-docker-android#158]
I am using the Appium Docker image to automate tests on an Android device. Is there a way to do the same thing for an iOS device? Currently, the Appium server is connecting to my machine that runs the Docker Compose project. Should I just start the Appium server on the Mac machine, or is there a way to achieve the same thing with Docker?

```
 appium_server:
    container_name: appium_server
    image: appium/appium
    depends_on:
      - selenium_hub
    ports:
      - "4725:4725"
      - "4723:4723"
    privileged: true
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    volumes:
      - ~/.android:/root/.android
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      - RELAXED_SECURITY=true
      - ANDROID_ADB_SERVER_ADDRESS=${HOST_IP}
      - ANDROID_ADB_SERVER_PORT=5037
      - SELENIUM_HOST=10.5.0.2
      - SELENIUM_PORT=4444
    command: appium -a 0.0.0.0 -p 4723 --relaxed-security --session-override
```
